### ISSUE TITLE
Can we use middot divider in inline links instead of vertical grey divider? (Juju)

### ISSUE THREAD

**Issue by yaili** [canonical-web-and-design/vanilla-store-theme-design#1]
Seen in links: Adjust | Terms and conditions

**Comment by yaili** [comment]
@spencerbygraves did you get a chance to look at this?

**Comment by spencerbygraves** [comment]
We use a dot in most cases, I'll check for lines and ask @Lukewh to update.

**Comment by yaili** [comment]
It does look like in the new designs it's always a dot.

**Comment by kwm14** [comment]
Juju now uses middot-sepearted inline list in charm details page - https://jujucharms.com/canonical-kubernetes/

In Vanilla we now have [inline list](https://docs.vanillaframework.io/en/patterns/lists#inline-list) and [middot-seperated inline list](https://docs.vanillaframework.io/en/patterns/lists#middot-separated-inline-list).

Closing issue as Juju have updated pattern and has also been applied to Snappy.

**Comment by yaili** [comment]
👍
