### ISSUE TITLE
Align content in title area/hero area

### ISSUE THREAD

**Issue by yaili** [canonical-web-and-design/vanilla-store-theme-design#4]
Everything aligns left, to the right of the icon, instead of the some things being below the icon as is the case of Juju now. This would make Juju align with Snapweb.

**Comment by spencerbygraves** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Charm Details page improvements](https://trello.com/c/K4B1v1Kz/779-charm-details-page-improvements)

**Comment by yaili** [comment]
@spencerbygraves did you work on this?

**Comment by spencerbygraves** [comment]
We've been working on some [improvements](https://github.com/CanonicalLtd/juju-design/issues/200) to details pages, we'll look to include it there.

**Comment by yaili** [comment]
OK. In the last iteration of those new designs some elements are under the logo, some elements are next to it. Would it be better to have them either all next to the logo or all under, and there would be just 2 variations of the pattern? If not, this issue would be invalid, I think, which can also happen if we think that's better.

**Comment by spencerbygraves** [comment]
I'm not keen on moving everything up next to the logo, as when we add in the bundle icon we'll have a lot of space below the icon, which looks odd I think.

![image](https://cloud.githubusercontent.com/assets/9105999/25741276/dd82ace8-3181-11e7-92bf-8ff2bcf2b7ec.png)

As there's more info on Juju than Snapweb, perhaps it's better to keep the title next to the icon with the other info below, and close this issue.

**Comment by yaili** [comment]
That makes sense: title next to icon, everything else below.
