### ISSUE TITLE
Do we need a utility to change text colour to grey?

### ISSUE THREAD

**Issue by yaili** [canonical-web-and-design/vanilla-store-theme-design#5]

**Comment by yaili** [comment]
@barrymcgee @deadlight this was also referenced for www.ubuntu.com

**Comment by kwm14** [comment]
I ran a test on ubuntu.com replacing our default text color of`$color-dark` to use `$color-mid-dark` our darkest grey in our color palette.	

The test report served 25 Errors and 22 Warnings, most highlighting accessibility issues with the font color: 

> This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.41:1

> This element's text is placed on a background image. Ensure the contrast ratio between the text and all covered parts of the image are at least 3:1

Good to have evidence of this. But it boils down to the use case of the grey and when/where we use it. If it's rarely used is there a need for a utility class to change text to grey?

**Comment by kwm14** [comment]
Discussion with @spencerbygraves and @anthonydillon, agreed that we currently don't need a utility to change text colour to grey. By default we use out default of `$color-dark` and in one-off use cases we may use the grey.

If and when begin to use grey as a text colour we will re-visit this issue.
