### ISSUE TITLE
Design proposal for tabs in small screen

### ISSUE THREAD

**Issue by yaili** [canonical-web-and-design/vanilla-store-theme-design#6]
Use designs from platform/Snapweb.

**Comment by kwm14** [comment]
## Closing issue

Work for this proposal was completed during our Dashboard mini sprint. Tabs will be moved to base Vanilla during the next iteration, once we migrate all Dashboard theme components.

- Design spec for tabs can be found [here.](https://github.com/ubuntudesign/vanilla-dashboard-theme-design/tree/master/Tabs)
- Built and merged during Dashboard mini sprint [here.](https://github.com/vanilla-framework/vanilla-dashboard-theme/pull/17)
