### ISSUE TITLE
Expand footer pattern

### ISSUE THREAD

**Issue by yaili** [canonical-web-and-design/vanilla-store-theme-design#7]
_From @yaili on May 30, 2017 9:24_

[Notes from workshop](https://github.com/ubuntudesign/meeting-notes/issues/155):
- Expand current Vanilla footer to include more elements

_Copied from original issue: ubuntudesign/vanilla-brochure-theme-design#22_

**Comment by kwm14** [comment]
Reading through **meeting notes** and tracked **issues** there isn't much context on elements needed to add to our current footer.

Looking at our marketing and associated Cloud websites we're all pretty consistent in terms of elements inside the footer.

- Registered trademarks
- Legal information
- Report a bug
- Social

Closing for now until a new use case arises that we need more elements inside our current footer pattern.
