### ISSUE TITLE
Create spec for step-indicator pattern

### ISSUE THREAD

**Issue by yaili** [canonical-web-and-design/vanilla-store-theme-design#8]
_From @yaili on May 30, 2017 9:23_

[Notes from workshop](https://github.com/ubuntudesign/meeting-notes/issues/155):
- Agreed name: **step-indicator** (`p-step-indicator`)
  - States: default, information, positive, caution, negative (same as [notifications](https://github.com/ubuntudesign/vanilla-design/tree/master/Notifications))

Related to: https://github.com/ubuntudesign/vanilla-brochure-theme-design/issues/20

_Copied from original issue: ubuntudesign/vanilla-brochure-theme-design#21_

**Comment by kwm14** [comment]
@yaili would you be able to provide any more information in regards to the states listed above? I know it was over 5 months ago :slightly_smiling_face:

Speaking with the team they believe this component is referencing [stepped list](https://docs.vanillaframework.io/en/patterns/lists#stepped-lis )?

**Comment by matthewpaulthomas** [comment]
Given that it was for “Confirmation/progress” in a “Store theme”, maybe it was a [step progress indicator as commonly used in store checkouts](http://www.pitstopmedia.com/sem/checkout-progress-bar-survey). We introduced an indicator like this to reassure people through their first use of build.snapcraft.io.

**Comment by anthonydillon** [comment]
It is the process inductor in the checkout/setup process. I'm not sure we still use this pattern?

**Comment by yaili** [comment]
I don't think it's any of those, based on the [photo](https://photos.app.goo.gl/3oewBzxGhQuAKv6h1) from the workshop. I think it's related to the "tick" icon in the headers.

**Comment by yaili** [comment]
The "related to" link in the OP is redirecting somewhere else for me, so I don't know what that link was about. :(

**Comment by spencerbygraves** [comment]
I believe it's [this pattern](https://docs.vanillaframework.io/en/patterns/lists#stepped-list), as we previously had more than one version.

**Comment by kwm14** [comment]
Thanks everyone for your comments. We've decided to close this issue for now until we have a need to add this component into the framework.
